### ISSUE TITLE
Wens #2: Toevoegen van extra velden

### ISSUE THREAD

**Issue by lemodesign** [hoest/knvb-api#10]
De data die uit de API komt word toegevoegd via "SportLink". Als ik in het systeem van SportLink kijk zie ik daar een aantal values staan die ik niet terug kan vinden in de plugin. Is dit omdat het niet mogelijk is of omdat de API dit niet toe staat?

Vertrektijd
Vervoer
Scheidsrechter
Accommodatie

**Comment by hoest** [comment]
Alles wat ingevoerd wordt, kan ook weer getoond worden, maar om de tabellen een beetje overzichtelijk te houden, heb ik er voor gekozen alleen de informatie te tonen die er (voor alle clubs die de plugin nu gebruiken) toe doen.
