### ISSUE TITLE
Volgorde wedstrijden

### ISSUE THREAD

**Issue by lemodesign** [hoest/knvb-api#11]
De volgorde van de wedstrijden kloppen niet, dit gaat niet op tijd en datum maar op thuis of uit wedstrijden. Ik neem aan dat dit op datum en tijd moet ongeacht of het uit of thuis wedstrijden zijn.

<h5>De huidige situaties is als volgt:</h5>
<ul>
<li>11-04-2015 om 13:30 uur
<strong>Thuis team - Uit team</strong></li>

<li>11-04-2015 om 12:00 uur
<strong>Uit team - Thuis team</strong></li>

<li>11-04-2015 om 13:30 uur
<strong>Thuis team - Uit team</strong></li>

<li>11-04-2015 om 11:30 uur
<strong>Uit team - Thuis team</strong></li>
</ul>

<h5>Dit zou eigenlijk zo moeten zijn:</h5>
<ul>
<li>11-04-2015 om 13:30 uur
<strong>Thuis team - Uit team</strong></li>

<li>11-04-2015 om 13:30 uur
<strong>Thuis team - Uit team</strong></li>

<li>11-04-2015 om 12:00 uur
<strong>Uit team - Thuis team</strong></li>

<li>11-04-2015 om 11:30 uur
<strong>Uit team - Thuis team</strong></li>
</ul>
Is dit een bug? Of een fout in de instellingen?

**Comment by hoest** [comment]
Beide opties zijn mogelijk met de `thuis` parameter:

Toon alle wedstrijden

```
[knvb uri="/wedstrijden" extra="weeknummer=A"]
```

Toon alle wedstrijden, thuis- en uitwedstrijden gesplitst

```
[knvb uri="/wedstrijden" extra="weeknummer=A&thuis=1"]
```
