### ISSUE TITLE
Vraag van @nicoo1968

### ISSUE THREAD

**Issue by hoest** [hoest/knvb-api#13]
Hallo Jelle,

Als de plugin verder goed werkt dan heb ik nog wel een vraagerover. Ik gebruik de KNVB api plugin op http://hfc15.nl  en heb voor alle commando’s een pagina gemaakt http://hfc15.nl/senioren/zondag-5/zondag-2/test-programma/ zodat ik kan zien of speelschema’s ook ingevuld worden wat namelijk nu niet het geval is.

Komt dit vanzelf (dus een paar week voor de wedstrijd) of doe ik iets verkeerd met de toegepaste codes? want hij geeft wel helemaal onder wel alle te spelen wedstrijden weer maar niet individueel per team.

Ik hoop dat je kunt helpen.

Met vriendelijke groet,
Nico

**Comment by hoest** [comment]
Hoi Nico,

De diverse tags waarin je weeknummer=C of weeknummer=N e.d., kunt gebuiken gaan over de huidige week en de volgende week. Dus alles in de context van de huidige datum. Vandaag (29 juli 2015) is er nog nauwelijks een programma beschikbaar.

Zoals je ook op je testpagina kunt zien heb je bij weeknummer=A wel gewoon duidelijk een overzicht met alle komende wedstrijden. En bij HFC'15 starten deze op 8 augustus, bij mijn vereniging starten ze pas op 22 augustus.

Zodra de tijd daar is, zullen de programma's ook werkelijk gevuld gaan worden. Maar zoals ook in mijn beschrijving staat beschreven, is dat de werking voor bijvoorbeeld weeknummer=C echt alleen voor de huidige week is.

Hopelijk heb ik je hiermee kunnen helpen.

Op de site van mijn vereniging is te zien dat alles correct lijkt te werken:
http://www.vvz49.nl/selectie/vvz49-1-stand-uitslagen/

Groeten,
Jelle

**Comment by nicoo1968** [comment]
Okee ik ben gewoon een beetje te ongeduldig komt ook door de voetbalde weekends haha. maar de pagina van jouw vereniging ziet er trouwens gelikt uit, krijg ik dat straks ook zo te zien of komt daar nog wat ander programmeerwerk bij kijken ?

**Comment by hoest** [comment]
Dit is door wat extra programmeerwerk en styling te realiseren ;-) Dit heeft weer iemand anders verzorgd.

**Comment by nicoo1968** [comment]
Hoi Jelle,

Ik heb toch wat problemen met het plaatsen van de slider en het zichtbaar worden van de wedstrijden. Ik ben al een stuk verder maar als ik kijk bij jou vereniging dan is alles al zichtbaar en heb jij de slider daar werkend. Ik vermoed dat ik ook alle wedstrijden zichtbaar krijg middels de slider, maar ik krijg hem met geen mogelijkheid aan de praat op mijn site. zou jij ook kunnen zien wat ik verkeerd doe door misschien eens een kijkje te nemen op de site o.i.d.

Met vriendelijke groet,

Nico

**Comment by hoest** [comment]
Nico, wil je me hier [even over mailen](http://jelledejong.org)?
