### ISSUE TITLE
Wedstrijdoverzicht op teamniveau (KNVB API)

### ISSUE THREAD

**Issue by hribbers** [hoest/knvb-api#14]
Beste Jelle / L.S.

Ik heb gezien dat er vandaag wat communicatie was op github over de KNVB-API.
Ik wilde je graag een vraag stellen over de wedstrijdschema's. 

Situatie:
De volgende shortvode geeft een overzicht (totaaloverzicht) van alle wedstrijden van alle teams:
[knvb uri="/wedstrijden" extra="weeknummer=A"]

Dit werkt correct.

Als ik echter per team een vergelijkbaar schema wil opvragen geeft hij aan:
"Geen wedstrijdschema beschikbaar". 
Dit schema vraag ik op met de volgende schortcodes:
[knvb uri="/teams/142760/schedule"]
of (probeersel)
[knvb uri="/teams/142760/schedule" extra="weeknummer=A"]

Er komen geen wedstrijden tevoorschijn. Dit terwijl er weldegelijk wedstrijden zichtbaar zijn in het totaaloverzicht. (ter info, dit zijn allemaal bekerwedstrijden, mogelijk heeft het hier iets mee te maken)
De ranking werkt wel bij alle teams, dus de ID's lijken goed te zijn. Deze staan vermeld op de KNVB configuratiepagina in Wordpress.

Al met al de vraag, wat doe ik verkeerd of wat gaat er fout.
Ik hoor uiterst graag van je!

Erik

**Comment by hoest** [comment]
Erik, ik denk inderdaad dat het er mee te maken heeft dat competitie- en bekerwedstrijden anders tonen en deze laatste niet terugkomen op team-niveau. De team-overzichten zijn echt alleen voor competitie-doeleinden.
