### ISSUE TITLE
Wens: uit en aanzetten van kolommen 

### ISSUE THREAD

**Issue by ritchietomasouw** [hoest/knvb-api#15]
Het zou mooi zijn als je ergens (het mooiste via de backend of shortcode) kan aangeven welke kolommen je allemaal zichtbaar wilt hebben. Bijvoorbeeld je wilt een complete stand met alle kolommen, maar ergens anders op de site wil je een stand met alleen de positie, teamnaam en punten (dus slechts 3 kolommen). Dit geldt dan ook voor het programma en uitslagen.

Is dit te realiseren? :+1:  :)

**Comment by hoest** [comment]
Lastig, maar ik leg het even in de week! :)

**Comment by ritchietomasouw** [comment]
Jelle, 

ik zou dit (als workaround) kunnen oplossen via CSS als elke <td> ook een CLASS heeft.
Ik zou dan een "@media screen" kunnen gebruiken en de de kolommen die ik niet wil zien op display:none zetten.

In de diverse templates (ranking, schedule, etc) staan een aantal td zonder CLASS.  Kan jij ervoor zorgen dat elke <td> ook een CLASS krijgt? Bijvoorbeeld: in de ranking.html mis ik een class bij positie (1e kolom) en de TD img (clublogo, 2e kolom) en een bij de laatste kolom, dpv - dpt.

**Comment by hoest** [comment]
Dit kan ik eerdaags wel oppakken.

**Comment by hoest** [comment]
Iedere tabel-cel heeft een eigen class gekregen, hiermee zou je via CSS kolommen aan/uit kunnen zetten.

Beschikbaar vanaf versie 1.10

**Comment by ritchietomasouw** [comment]
Yep het werkt :+1:  Al toegepast op de VVZ49.nl website (programma, uitslagen en standen). Top!

**Comment by MarcXP** [comment]
@ritchietomasouw - Gelijk uit nieuwsgierigheid een kijkje op jullie site genomen. Wauw! dat ziet er gaaf uit! Ik ga dat ook eens bij ons proberen te realiseren!

@hoest - Dank je voor het aanpassen van de code!
