### ISSUE TITLE
Wie kan me helpen

### ISSUE THREAD

**Issue by nicoo1968** [hoest/knvb-api#16]
Hallo,

Ik heb een probleem en misschien hebben jullie dit probleem ook gehad en kunnen me helpen aan een oplossing.

Als ik een code plaats: [knvb uri="/wedstrijden" extra="weeknummer=C"] 
dan krijg ik keurig alle wedstrijden van komende week te zien.

Als ik een code plaats: [knvb uri="/wedstrijden" extra="weeknummer=C&comptype=B"] 
dan krijg ik keurig alle wedstrijden uit de beker competitie te zien

Als ik een code plaats: [knvb uri="/wedstrijden" extra="weeknummer=C&logo=1"]
 Dan krijg ik alle wedstrijden van komende week te zien met logo's van de teams.

Als ik een code plaats: [knvb uri="/wedstrijden" extra="weeknummer=C&comptype=B&logo=1"]
Dan krijg ik alle wedstrijden van komende week te zien met logo's van de teams van de bekerwedstrijden.

Als ik een code plaats: 
[knvb uri="/wedstrijden" extra="weeknummer=C&thuis=1"] of 
[knvb uri="/wedstrijden" extra="weeknummer=C&thuis=1&thuisonly=1"] of 
[knvb uri="/wedstrijden" extra="weeknummer=C&comptype=B&thuis=1&thuisonly=1"]

Dan krijg ik de melding: Momenteel is er geen wedstrijdenoverzicht beschikbaar.

Ik heb al van alles geprobeerd en elke mogelijke combinatie al gedaan en zelfs alle plugins van de site al uitgeschakeld behalve die van KNVB api maar niets hielp.

wie kan me helpen aan de oplossing?

**Comment by MarcXP** [comment]
Ik ben er ook achter dat de toevoeging &thuis=1 de foutcode geeft. Wij gebruiken:

[knvb uri="/wedstrijden" extra="weeknummer=C&thuisonly=1"]

Hierbij krijg ik een - op datum en tijd - gesorteerde lijst. Maar wel van thuis en uitwedstrijden door elkaar en dus niet uitsluitend de thuiswedstrijden die ik wel zou willen zien.

**Comment by hoest** [comment]
Volgens mij moet je thuisonly=1 combineren met thuis=1. Probeer dat eens?

Groeten
Jelle


Op dinsdag 6 oktober 2015 heeft MarcXP <notifications@github.com> het
volgende geschreven:

**Comment by nicoo1968** [comment]
Heren ik ben echt super blij met een reactie want zit hier wel mee in mijn maag, maar de beide opties werken niet bij mij. Ik heb een testpagina gemaakt en beide opties ingevuld op: http://hfc15.nl/beeldscherm_hal_test/ de datum staat wel gesorteerd maar de tijden allemaal door elkaar

**Comment by hoest** [comment]
Dan moet je waarschijnlijk even updaten naar de laatste versie. Daarin zit
een fix voor de sortering.

Op dinsdag 6 oktober 2015 heeft Nico Kranenburg <notifications@github.com>
het volgende geschreven:

**Comment by hoest** [comment]
Als ik onderstaande codes gebruik in een schone WordPress installatie met de meest recente versie van de plugin (nl. v1.10), dan gaat alles gewoon goed:

```
[knvb uri="/wedstrijden" extra="weeknummer=C&thuis=1"]
[knvb uri="/wedstrijden" extra="weeknummer=C&thuis=1&thuisonly=1"]
[knvb uri="/wedstrijden" extra="weeknummer=C&comptype=B&thuis=1&thuisonly=1"]
```

Ik krijg overal resultaten.

**Comment by MarcXP** [comment]
Ik heb de laatste versie geïnstalleerd (v.1.10) in combinatie met een volledig geupdate WordPress installatie. Maar bij de shortcode:

 [knvb uri="/wedstrijden" extra="weeknummer=C&thuis=1&thuisonly=1"]

krijg ik als output:

Fatal error: Using $this when not in object context in /home/tsc/domains/vvtsc.nl/public_html/wp-content/plugins/knvb-api/knvb-client.php on line 124

**Comment by hoest** [comment]
Heb je in het instellingen scherm van de Plugin wel de correcte gegevens ingevoerd, met name de 'Clubnaam'?

```
/wp-admin/options-general.php?page=knvb-api-menu
```

De clubnaam die je hier invult wordt namelijk gebruikt om te controleren of het om een uit of thuis wedstrijd gaat. Dus deze moet ingevuld zijn en ook terug te vinden zijn in de overzichten van de KNVB, zodat daarop gefilterd kan worden.

**Comment by nicoo1968** [comment]
Ik weet niet wat er fout gaat maar krijg nu na de update evan de plugin helemaal geen resultaten meer terwijl ik die voorheen wel kreeg en alleen de sortering van de aanvangstijden nog een probleem was.

lijkt erop dat ik terug moet naar de vorige versie

**Comment by nicoo1968** [comment]
en na toch nog opnieuw de plugin te hebben gedeinstalleerd en weer opnieuw geïnstalleerd krijg ik gelukkig wel de goede resultaten

top

**Comment by MarcXP** [comment]
@hoest ; Dat is inderdaad vreemd... De clubnaam die in het totaaloverzicht (uit en thuis) voorkomt is 'TSC'. Deze naam staat ook in de KNVB API opties. Dus snap ik niet waar de fout kan liggen.

Overigens zie ik in knvb-client.php in regel 15 hardcoded: #clubName = 'VVZ /'49' staan! Deze heb ik maar aangepast, helaas zonder resultaat

**Comment by hoest** [comment]
@MarcXP Ik heb je een mail gestuurd om even gezamenlijk te zoeken naar een oplossing.

**Comment by nicoo1968** [comment]
Bij mijn werkt het inmiddels helemaal super.

Ik heb nog wel een vraag voor de wishlist. Is het ook mogelijk een sortering te maken op datum en team net zoals het nu is op datum en tijd zodat dit verschillend toegepast kan worden op de site.

Bedankt voor de moeite en het meedenken !

**Comment by hoest** [comment]
@nicoo1968 : Mooi zo! Wat betreft je wens, hiervoor mag je een apart issue toevoegen en dan komt het misschien in een eerstvolgende release, wanneer het uitvoerbaar is natuurlijk.
