### ISSUE TITLE
Laad tijd

### ISSUE THREAD

**Issue by Leevaim** [hoest/knvb-api#18]
Beste,

Ik probeer de stand van een team op te halen. Maar het duurt zeker enkele seconden laadtijd voordat de info geplaatst wordt. Waar kan dit aan liggen?

Alvast bedankt!

**Comment by hoest** [comment]
Met behulp van welke shortcode in WordPress?

**Comment by Leevaim** [comment]
Is al opgelost. Had te maken met een fout in een loop in mijn custom code.
