### ISSUE TITLE
Kan deze plugin werken in Joomla?

### ISSUE THREAD

**Issue by benscharft** [hoest/knvb-api#19]
Ik heb een joomla site, is deze plugin daar ook voor geschikt?

Zo niet, hoe krijg ik deze wel aan de praat?

**Comment by hoest** [comment]
Deze plugin is momenteel alleen geschikt voor WordPress. Je mag de code gebruiken als voorbeeld voor een implementatie in Joomla, alleen kan ik je daar verder niet mee helpen.
