### ISSUE TITLE
Wedstrijdoverzicht sorteren

### ISSUE THREAD

**Issue by MarcXP** [hoest/knvb-api#20]
Momenteel gebruiken wij op onze site de code

[knvb uri="/wedstrijden" extra="weeknummer=C&thuisonly=1"]

om wedstrijen weer te geven. Alleen staan alle elftallen zonder logische indeling door elkaar heen. Is er een mogelijkheid om een sorteervolgorde aan te geven of anders ergens in de PHP code te verwerken zodat de elftallen keurig op volgorde komen te staan?

**Comment by hoest** [comment]
Moet opgelost zijn vanaf de 1.9 release

**Comment by MarcXP** [comment]
Super! Ik ga het meteen uit testen!
