### ISSUE TITLE
Versing van de API

### ISSUE THREAD

**Issue by Leevaim** [hoest/knvb-api#22]
Hoi,

Ik ben de KNVB-API aan het verwerken in een website. Hierbij wil ik de uitslagen direct nadat ze bekend zijn weergeven. Is dit mogelijk met de API of wordt de API per week ververst omdat je dit mee kan geven in de apicall? 

Alvast bedankt!

**Comment by hoest** [comment]
De plugin heeft een cache van volgens mij 15 minuten tot 1 uur... verder zal de data vanuit de KNVB-API opgehaald worden. Dus wanneer het daar beschikbaar is, zal het ook door de plugin opgepakt worden.
