### ISSUE TITLE
[knvb uri="/teams/106698/schedule"] geef alleen de volgende wedstrijd

### ISSUE THREAD

**Issue by luttyfrutty** [hoest/knvb-api#24]
Jelle,

Als ik de volgende shortcode gebruik dan krijg ik alleen de volgende wedstrijd, maar niet de wedstrijden daarna.

<?php echo do_shortcode( '[knvb uri="/teams/212096/schedule" extra="logo=1"]' ); ?>

Wat moet ik doen om de andere wedstrijden voor een team ook zichtbaar te krijgen.

Alvast bedankt!

Robin Lutteke

**Comment by hoest** [comment]
@luttyfrutty wil jij mij misschien een mail sturen met daarin je API-sleutel? Dan kan ik even kijken of ik de fout kan reproduceren.

Vast bedankt!

**Comment by hoest** [comment]
Door gebruik te maken van `[knvb uri="/teams/.../schedule" extra="weeknummer=A"]` krijg je alle komende wedstrijden.
