### ISSUE TITLE
Tabel headers voor stand/uitslagen/programma

### ISSUE THREAD

**Issue by larslenselink** [hoest/knvb-api#25]
Dag Jelle,

Allereerst, super plugin! Erg handig voor de nieuwe site van onze voetbalclub. Ik ben bezig met de tabellen voor de stand, uitslagen en programma en merkte dat de tabel headers die vertellen wat er in de  kolommen er onder wordt weergegeven (team, gespeeld, punten, goals voor, goals tegen, etc.). Is er een mogelijkheid om deze er met jouw plugin alsnog in te krijgen? (http://www.projectarthouse.nl/vvruurlo/elftallen/senioren/ruurlo-1/)

Alvast bedankt!

Met vriendelijke groet,
Lars Lenselink

**Comment by larslenselink** [comment]
Heb de oplossing al gevonden. Door in het template een nieuwe rij aan te maken met de corresponderende header titels en deze een eigen class mee te geven is dit te realiseren. Voor de stand weergave krijg je dan bijvoorbeeld:

`<table class="ranking">
<tr class="thead">
        <td class="position">#</td>
        <td class="name">Team</td>
        <td class="played" title="Gespeeld">Gespeeld</td>
        <td class="won" title="Gewonnen">W</td>
        <td class="tie" title="Gelijk">G</td>
        <td class="lost" title="Verloren">V</td>
        <td class="points" title="Punten">P</td>
        <td class="goals">GV - GT</td>
    </tr>
{loop="$data"}
  <tr{if="substr($value->naam, 0, 4) == 'VVZ '"} class="self trow"{/if}>
    <td class="position">{$value->Positie}</td>
    {if="$logo"}<td class="logo">{if="$value->logo"}<img alt="Clublogo van {$value->naam}" src="{$value->logo}" />{/if}</td>{/if}
    <td class="name">{$value->naam}</td>
    <td class="played" title="Gespeeld">{$value->Gespeeld}</td>
    <td class="won" title="Gewonnen">{$value->Gewonnen}</td>
    <td class="tie" title="Gelijk">{$value->Gelijk}</td>
    <td class="lost" title="Verloren">{$value->Verloren}</td>
    <td class="points" title="Punten">{$value->Punten}</td>
    <td class="goals">({$value->DoelpuntenVoor} - {$value->DoelpuntenTegen})</td>
  </tr>
{else}
  <tr>
    <td class="nothing">Momenteel is er geen stand beschikbaar.</td>
  </tr>
{/loop}
</table>`

**Comment by hoest** [comment]
Wanneer #27 is goedgekeurd, kun je in je eigen template bestand kolommen gemakkelijk toevoegen.
