### ISSUE TITLE
Template aanpassing

### ISSUE THREAD

**Issue by larslenselink** [hoest/knvb-api#27]
Beste,

Ik probeer de dataweergave van een template (schedule.html) te wijzigen zodat de data niet meer in een tabel maar in een lijst of div wordt weergegeven. Ik heb hiervoor een nieuw html bestand aangemaakt in de template folder. Hoe zorg ik ervoor dat ik deze nu middels een short code kan weergeven. 

Stel de nieuwe template heet programma.html, hoe kan ik deze dan aanroepen? 

Alvast bedankt!

**Comment by hoest** [comment]
Hi @larslenselink 

Wil het lukken om zelf die html te bouwen zodat ik het in een release voor je kan ontsluiten?

Groeten,
Jelle

**Comment by hoest** [comment]
Hoi Lars,

Zie m'n mail van vandaag, maar het is testklaar:
https://github.com/hoest/knvb-api#eigen-templates

Is dit OK?

**Comment by hoest** [comment]
OK bevonden!
