### ISSUE TITLE
Teams worden niet meer opgehaald

### ISSUE THREAD

**Issue by kim-smitje** [hoest/knvb-api#28]
Hierdoor kan ik de teamid's niet meer achterhalen

**Comment by MarcXP** [comment]
Zit met hetzelfde probleem dat in het beheerdersgedeelte een foutmelding komt op de plaats waar de lijst met teamid's zou moeten verschijnen.

Daarnaast krijg ik geen standen meer te zien, terwijl de uitslagen en het programma wel normaal functioneren.

**Comment by hoest** [comment]
Zojuist een fix gereleased in release 1.12.

**Comment by hoest** [comment]
Is dit naar wens?

**Comment by kim-smitje** [comment]
Zo ja helemaal top!
Bedankt!!!

**Comment by hoest** [comment]
Fijn te horen! Veel plezier met de plugin!
