### ISSUE TITLE
Wedstrijden en standen worden niet meer opgehaald

### ISSUE THREAD

**Issue by MarcXP** [hoest/knvb-api#29]
Sinds de laatste update lopen alle standen en wedstrijden helemaal vast op onze website.

**Wedstrijden**:
Normaal gesproken gebruikte ik de volgende code om alleen de thuiswedstrijden voor komend weekend te laten zien:
`[knvb uri="/wedstrijden" extra="weeknummer=C&thuis=1&thuisonly=1"]`

Sinds de update krijg ik de volgende foutmelding:
`Fatal error: Using $this when not in object context in /wp-content/plugins/knvb-api/knvb-client.php on line 124`

Vandaar dat ik het stukje **&thuis=1&thuisonly=1** heb verwijderd waardoor ik in ieder geval wel de wedstrijden zie. Maar helaas uit en thuiswedstrijden door elkaar heen.

**Standen**:
Ook de standen worden niet meer geladen.
Hier gebruik ik de standaardcode maar zie ik geen resultaat:
`[knvb uri="/teams/180646/ranking"]`

Voorbeeld (onder de teamfoto) : [http://www.vvtsc.nl/teams/pupillen/tsc-d4/](url)

**Comment by hoest** [comment]
Ik heb een fix gerealiseerd in 1.12; is dit probleem nu opgelost?
