### ISSUE TITLE
veld zaal

### ISSUE THREAD

**Issue by wsddsoest** [hoest/knvb-api#30]
Hallo Jelle,

Ten eerste mijn complimenten voor top plug-ins. 
Ik denk dat veel mensen hier erg blij mee zullen zijn inclusief mij zelf.

Ik heb alleen wel een probleem met de zal en veld wedstrijden te scheiden.
Dit zou moeten kunnen om achter extra=weeknummer=C&zaalveld=vel te zetten.
Maar bij mij doet hij dan niks.

Alvast bedankt voor het mee denken!

Vriendelijke groeten,
Marcel Westemijer
VV SEC  Soest

**Comment by hoest** [comment]
Hoi Marcel,

Ik heb een update uitgebracht, namelijk versie 1.12; speelt dit probleem nu nog?
