### ISSUE TITLE
Standen halve competities

### ISSUE THREAD

**Issue by larslenselink** [hoest/knvb-api#31]
Goedemiddag! Op onze website (http://www.vvruurlo.nl/elftallen/junioren/ruurlo-c2/) worden de standen voor alle teams die een halve competitie spelen niet getoond (uitslagen en programma wel). Hoe kan ik dit oplossen?

**Comment by mmli** [comment]
Hallo Jelle, geweldige plugin. Superhandig. Maar inderdaad heb ik ook bovenstaand probleem. Alles werkt goed, behalve de standen van de jeugd competities. Als je een oplossing weet dan heel graag. Bedankt.

**Comment by hoest** [comment]
Hoi @larslenselink en @mmli 

Ik zie het probleem op jullie site. Ik ga proberen eerdaags eens te kijken wat de oorzaak hiervan is.

Ik kom er op terug!

**Comment by thepercival** [comment]
Ik heb even gekeken, de json die wordt teruggegeven is raar(zie hieronder de json van een jeugdcompetitie(najaar)). Er wordt voor elk team een getal gezet. Dit is niet zo bij seniorenteams. Vervolgens begrijpt de template de json dus niet. Hopelijk heb je hier wat aan.

{"errorcode":1000,"message":"Ok, Ranking follows","List":[{"pouleid":"445711","0":{"naam":"JVC Dedemsvaart F5","TeamID":"229978","logo":"http:\/\/bin617.website-voetbal.nl\/sites\/voetbal.nl\/files\/knvblogos\/NXTG27X.png","Positie":1,"Gespeeld":5,"Gewonnen":5,"Gelijk":0,"Verloren":0,"Punten":15,"DoelpuntenVoor":30,"DoelpuntenTegen":10,"PuntenMindering":0,"CompType":null,"CompNummer":"OO-0277**-14-445711!","WedstrijdDag":"ZA","Periode":"S"},"1":{"naam":"SVI F5","TeamID":"168302","logo":"http:\/\/bin617.website-voetbal.nl\/sites\/voetbal.nl\/files\/knvblogos\/BBKV956.png","Positie":2,"Gespeeld":5,"Gewonnen":4,"Gelijk":0,"Verloren":1,"Punten":12,"DoelpuntenVoor":21,"DoelpuntenTegen":17,"PuntenMindering":0,"CompType":null,"CompNummer":"OO-0277**-14-445711!","WedstrijdDag":"ZA","Periode":"S"},"2":{"naam":"Nieuwleusen SV F3","TeamID":"161298","logo":"http:\/\/bin617.website-voetbal.nl\/sites\/voetbal.nl\/files\/knvblogos\/BBKV808.png","Positie":3,"Gespeeld":4,"Gewonnen":3,"Gelijk":1,"Verloren":0,"Punten":10,"DoelpuntenVoor":10,"DoelpuntenTegen":3,"PuntenMindering":0,"CompType":null,"CompNummer":"OO-0277**-14-445711!","WedstrijdDag":"ZA","Periode":"S"},"3":{"naam":"ZAC F4","TeamID":"165742","logo":"http:\/\/bin617.website-voetbal.nl\/sites\/voetbal.nl\/files\/knvblogos\/BBKY56A.png","Positie":4,"Gespeeld":4,"Gewonnen":3,"Gelijk":0,"Verloren":1,"Punten":9,"DoelpuntenVoor":22,"DoelpuntenTegen":9,"PuntenMindering":0,"CompType":null,"CompNummer":"OO-0277**-14-445711!","WedstrijdDag":"ZA","Periode":"S"},"4":{"naam":"Rohda R. F7","TeamID":"163987","logo":"http:\/\/bin617.website-voetbal.nl\/sites\/voetbal.nl\/files\/knvblogos\/BBKT85R.png","Positie":5,"Gespeeld":5,"Gewonnen":3,"Gelijk":0,"Verloren":2,"Punten":9,"DoelpuntenVoor":18,"DoelpuntenTegen":12,"PuntenMindering":0,"CompType":null,"CompNummer":"OO-0277**-14-445711!","WedstrijdDag":"ZA","Periode":"S"},"5":{"naam":"Zwolle SV F2","TeamID":"168058","logo":"http:\/\/bin617.website-voetbal.nl\/sites\/voetbal.nl\/files\/knvblogos\/BBKW722.png","Positie":6,"Gespeeld":5,"Gewonnen":3,"Gelijk":0,"Verloren":2,"Punten":9,"DoelpuntenVoor":15,"DoelpuntenTegen":11,"PuntenMindering":0,"CompType":null,"CompNummer":"OO-0277**-14-445711!","WedstrijdDag":"ZA","Periode":"S"},"6":{"naam":"USV F2","TeamID":"161634","logo":"http:\/\/bin617.website-voetbal.nl\/sites\/voetbal.nl\/files\/knvblogos\/BBKV71U.png","Positie":7,"Gespeeld":4,"Gewonnen":1,"Gelijk":2,"Verloren":1,"Punten":5,"DoelpuntenVoor":7,"DoelpuntenTegen":7,"PuntenMindering":0,"CompType":null,"CompNummer":"OO-0277**-14-445711!","WedstrijdDag":"ZA","Periode":"S"},"7":{"naam":"ASC '62 F5","TeamID":"198219","logo":"http:\/\/bin617.website-voetbal.nl\/sites\/voetbal.nl\/files\/knvblogos\/BBKV34L.png","Positie":8,"Gespeeld":5,"Gewonnen":1,"Gelijk":1,"Verloren":3,"Punten":4,"DoelpuntenVoor":11,"DoelpuntenTegen":14,"PuntenMindering":0,"CompType":null,"CompNummer":"OO-0277**-14-445711!","WedstrijdDag":"ZA","Periode":"S"},"8":{"naam":"SEH F4M","TeamID":"157331","logo":"http:\/\/bin617.website-voetbal.nl\/sites\/voetbal.nl\/files\/knvblogos\/BBKR89L.png","Positie":9,"Gespeeld":5,"Gewonnen":1,"Gelijk":1,"Verloren":3,"Punten":4,"DoelpuntenVoor":13,"DoelpuntenTegen":21,"PuntenMindering":0,"CompType":null,"CompNummer":"OO-0277**-14-445711!","WedstrijdDag":"ZA","Periode":"S"},"9":{"naam":"Genemuiden SC F5","TeamID":"95054","logo":"http:\/\/bin617.website-voetbal.nl\/sites\/voetbal.nl\/files\/knvblogos\/BBBF52I.png","Positie":10,"Gespeeld":5,"Gewonnen":1,"Gelijk":0,"Verloren":4,"Punten":3,"DoelpuntenVoor":5,"DoelpuntenTegen":22,"PuntenMindering":0,"CompType":null,"CompNummer":"OO-0277**-14-445711!","WedstrijdDag":"ZA","Periode":"S"},"10":{"naam":"HTC F4","TeamID":"165515","logo":"http:\/\/knvbdataservice.nl\/sites\/all\/themes\/knvbdataservice\/images\/clublogo\/1456129689.png","Positie":11,"Gespeeld":4,"Gewonnen":0,"Gelijk":1,"Verloren":3,"Punten":1,"DoelpuntenVoor":5,"DoelpuntenTegen":16,"PuntenMindering":0,"CompType":null,"CompNummer":"OO-0277**-14-445711!","WedstrijdDag":"ZA","Periode":"S"},"11":{"naam":"Olympia'28 F3","TeamID":"90091","logo":"http:\/\/bin617.website-voetbal.nl\/sites\/voetbal.nl\/files\/knvblogos\/BBBC68C.png","Positie":12,"Gespeeld":5,"Gewonnen":0,"Gelijk":0,"Verloren":5,"Punten":0,"DoelpuntenVoor":9,"DoelpuntenTegen":24,"PuntenMindering":0,"CompType":null,"CompNummer":"OO-0277**-14-445711!","WedstrijdDag":"ZA","Periode":"S"}},{"pouleid":"420977","0":{"naam":"WVF F7","TeamID":"167325","logo":"http:\/\/bin617.website-voetbal.nl\/sites\/voetbal.nl\/files\/knvblogos\/BBKY50E.png","Positie":1,"Gespeeld":11,"Gewonnen":9,"Gelijk":1,"Verloren":1,"Punten":28,"DoelpuntenVoor":71,"DoelpuntenTegen":9,"PuntenMindering":0,"CompType":null,"CompNummer":"OO-0275**-14-420977!","WedstrijdDag":"ZA","Periode":"S"},"1":{"naam":"Dieze West F1","TeamID":"245190","logo":"http:\/\/api.knvbdataservice.nl\/images\/leeg-clublogo-schildje.png","Positie":2,"Gespeeld":11,"Gewonnen":9,"Gelijk":0,"Verloren":2,"Punten":27,"DoelpuntenVoor":67,"DoelpuntenTegen":9,"PuntenMindering":0,"CompType":null,"CompNummer":"OO-0275**-14-420977!","WedstrijdDag":"ZA","Periode":"S"},"2":{"naam":"ZAC F6","TeamID":"165744","logo":"http:\/\/bin617.website-voetbal.nl\/sites\/voetbal.nl\/files\/knvblogos\/BBKY56A.png","Positie":3,"Gespeeld":11,"Gewonnen":7,"Gelijk":3,"Verloren":1,"Punten":24,"DoelpuntenVoor":39,"DoelpuntenTegen":23,"PuntenMindering":0,"CompType":null,"CompNummer":"OO-0275**-14-420977!","WedstrijdDag":"ZA","Periode":"S"},"3":{"naam":"Berkum F8M","TeamID":"253017","logo":"http:\/\/bin617.website-voetbal.nl\/sites\/voetbal.nl\/files\/knvblogos\/BBKV74X.png","Positie":4,"Gespeeld":11,"Gewonnen":7,"Gelijk":2,"Verloren":2,"Punten":23,"DoelpuntenVoor":74,"DoelpuntenTegen":21,"PuntenMindering":0,"CompType":null,"CompNummer":"OO-0275**-14-420977!","WedstrijdDag":"ZA","Periode":"S"},"4":{"naam":"WVF F8","TeamID":"167315","logo":"http:\/\/bin617.website-voetbal.nl\/sites\/voetbal.nl\/files\/knvblogos\/BBKY50E.png","Positie":5,"Gespeeld":11,"Gewonnen":7,"Gelijk":2,"Verloren":2,"Punten":23,"DoelpuntenVoor":50,"DoelpuntenTegen":13,"PuntenMindering":0,"CompType":null,"CompNummer":"OO-0275**-14-420977!","WedstrijdDag":"ZA","Periode":"S"},"5":{"naam":"SVI F7G","TeamID":"168304","logo":"http:\/\/bin617.website-voetbal.nl\/sites\/voetbal.nl\/files\/knvblogos\/BBKV956.png","Positie":6,"Gespeeld":11,"Gewonnen":7,"Gelijk":1,"Verloren":3,"Punten":22,"DoelpuntenVoor":45,"DoelpuntenTegen":17,"PuntenMindering":0,"CompType":null,"CompNummer":"OO-0275**-14-420977!","WedstrijdDag":"ZA","Periode":"S"},"6":{"naam":"Genemuiden SC F5","TeamID":"95054","logo":"http:\/\/bin617.website-voetbal.nl\/sites\/voetbal.nl\/files\/knvblogos\/BBBF52I.png","Positie":7,"Gespeeld":11,"Gewonnen":4,"Gelijk":0,"Verloren":7,"Punten":12,"DoelpuntenVoor":26,"DoelpuntenTegen":49,"PuntenMindering":0,"CompType":null,"CompNummer":"OO-0275**-14-420977!","WedstrijdDag":"ZA","Periode":"S"},"7":{"naam":"Zalk F1G","TeamID":"164550","logo":"http:\/\/bin617.website-voetbal.nl\/sites\/voetbal.nl\/files\/knvblogos\/BBKW13J.png","Positie":8,"Gespeeld":11,"Gewonnen":3,"Gelijk":1,"Verloren":7,"Punten":10,"DoelpuntenVoor":31,"DoelpuntenTegen":51,"PuntenMindering":0,"CompType":null,"CompNummer":"OO-0275**-14-420977!","WedstrijdDag":"ZA","Periode":"S"},"8":{"naam":"Berkum F7","TeamID":"186564","logo":"http:\/\/bin617.website-voetbal.nl\/sites\/voetbal.nl\/files\/knvblogos\/BBKV74X.png","Positie":9,"Gespeeld":11,"Gewonnen":3,"Gelijk":1,"Verloren":7,"Punten":10,"DoelpuntenVoor":24,"DoelpuntenTegen":66,"PuntenMindering":0,"CompType":null,"CompNummer":"OO-0275**-14-420977!","WedstrijdDag":"ZA","Periode":"S"},"9":{"naam":"HTC F4","TeamID":"165515","logo":"http:\/\/knvbdataservice.nl\/sites\/all\/themes\/knvbdataservice\/images\/clublogo\/1456129689.png","Positie":10,"Gespeeld":11,"Gewonnen":2,"Gelijk":2,"Verloren":7,"Punten":8,"DoelpuntenVoor":36,"DoelpuntenTegen":51,"PuntenMindering":0,"CompType":null,"CompNummer":"OO-0275**-14-420977!","WedstrijdDag":"ZA","Periode":"S"},"10":{"naam":"Nieuwleusen SV F4","TeamID":"161311","logo":"http:\/\/bin617.website-voetbal.nl\/sites\/voetbal.nl\/files\/knvblogos\/BBKV808.png","Positie":11,"Gespeeld":11,"Gewonnen":1,"Gelijk":1,"Verloren":9,"Punten":4,"DoelpuntenVoor":21,"DoelpuntenTegen":89,"PuntenMindering":0,"CompType":null,"CompNummer":"OO-0275**-14-420977!","WedstrijdDag":"ZA","Periode":"S"},"11":{"naam":"Dos Kampen F6G","TeamID":"159760","logo":"http:\/\/bin617.website-voetbal.nl\/sites\/voetbal.nl\/files\/knvblogos\/BBKV57U.png","Positie":12,"Gespeeld":11,"Gewonnen":0,"Gelijk":0,"Verloren":11,"Punten":0,"DoelpuntenVoor":13,"DoelpuntenTegen":99,"PuntenMindering":0,"CompType":null,"CompNummer":"OO-0275**-14-420977!","WedstrijdDag":"ZA","Periode":"S"}}]}

**Comment by thepercival** [comment]
Je kan dus de json omzetten, zodat het een array wordt. Je kan ook de competitiecall gebruiken:

/competities/165515/OO/0277/14/445711/ranking

Voor het omzetten van de json, wil ik wel een voorzetje maken. Laat maar even weten.

**Comment by hoest** [comment]
Hoi @thepercival ,

Mocht je het evt. zelf al kunnen fixen, dan zie ik graag een pull-request tegemoet!
Het gaat mij op korte termijn niet lukken...

Vast bedankt!

**Comment by thepercival** [comment]
heb pull-request naar je gestuurd, meteen bestaande functies nog even getest.

**Comment by larslenselink** [comment]
Mooi dat er een oplossing komt! Wanneer worden de wijzigingen doorgevoerd in de plugin?

**Comment by hoest** [comment]
Hopelijk lukt het me vanavond om een nieuwe release met deze fix uit te brengen, houd je WordPress maar in de gaten.

**Comment by mmli** [comment]
Heb ik het mis of werkt de template functie nu niet meer? Volgens mij mist die in de nieuwe commit

**Comment by hoest** [comment]
Zoals je in de conversatie kunt lezen, is het pull-request nog niet opgenomen in een release.

**Comment by hoest** [comment]
Release 1.13 kan ieder moment beschikbaar zijn. Bedankt @thepercival

**Comment by thepercival** [comment]
Geen probleem,  elkaar helpen is alleen maar mooi.

Gr Coen
Op 18 apr. 2016 20:04 schreef "Jelle de Jong" <notifications@github.com>:
