### ISSUE TITLE
Parse error (line 66)

### ISSUE THREAD

**Issue by jappiej** [hoest/knvb-api#34]
Hi,
Als je de plugin in wordpress  versie 4.5.2–nl_NL wilt activeren krijg je deze melding.

**Parse error: syntax error, unexpected T_FUNCTION in C:\domains\xxxx.nl\subdomeinen\xxxx\wwwroot\wp-content\plugins\knvb-api\knvb-client.php on line 66**

Op de gehele plugin directory staat chmod 777

Enig idee wat de oplossing hiervoor is ?

Met vriendelijke groet,

J. Jansen

**Comment by hoest** [comment]
Welke versie van PHP is er geïnstalleerd op je server?

**Comment by jappiej** [comment]
php 5.2....

Updaten naar minimaal?

**Comment by hoest** [comment]
Volgens mij versie 5.4, zie http://php.net/manual/en/language.types.callable.php

In de genoemde regel staat het gebruik van de `usort()` functie met een `callable`.
