### ISSUE TITLE
[knvb uri="/wedstrijden" extra="weeknummer=A&thuis=1"]

### ISSUE THREAD

**Issue by MauriceBor** [hoest/knvb-api#7]
Werkt helaas niet. 
En is er een mogelijkheid om enkel en alleen thuiswedstrijden te weergeven?
Het idee is namelijk dat we de pagina willen weergeven bij ons in de kantine, en daar in laten zien welk team in welk kleedkamer moet omkleden.
Heb het zelf al een beetje kunnen aanpassen door in wedstrijden dit toe te voegen:
    <td>{if="$value->Kleedkamer_thuis"}{$value->Kleedkamer_thuis}{/if}</td>
      <td>{if="$value->Kleedkamer_uit"}{$value->Kleedkamer_uit}{/if}</td>

Ik hoor graag van je, en alvast bedankt!

**Comment by hoest** [comment]
Beste Maurice, wat werkt er precies niet? Zie je niets? En de instellingen in het Settings > KNVB API menu staan wel allemaal correct ingevuld? Zou je me anders eens willen mailen?

Wat betreft je aanpassing, dit is zeker mogelijk. Zal hier eens voor kijken.

**Comment by MauriceBor** [comment]
Beste Jelle,
De instellingen zijn juist ingevuld, en de resst werkt wel. Alleen deze specifieke tag werkt niet.Ik zie inderdaad niks, de pagina blijft leeg en doet zelfs een beetje vreemd.Met deze aanpassing zou je me in ieder geval uit de brand helpen, want hier loop ik nu nog het meeste tegen aan.
Hoor graag van je.Groet Maurice
Date: Tue, 3 Feb 2015 05:16:45 -0800

**Comment by hoest** [comment]
Beste Maurice, speelt dit probleem nog?

**Comment by nicoo1968** [comment]
Ben ook wel nieuwsgierig als dit is opgelost Maurice het lukt mij met gen mogelijkheid om de kleedkamer en veld informatie op de site te krijgen misschien kunnen we elkaar helpen.

**Comment by hoest** [comment]
Ik sluit dit incident, aangezien onderstaande code gewoon werkt in een schone WordPress met v1.10:

```
[knvb uri="/wedstrijden" extra="weeknummer=A&thuis=1&thuisonly=1"]
```
