### ISSUE TITLE
Wens #1: Extra templates

### ISSUE THREAD

**Issue by lemodesign** [hoest/knvb-api#9]
Na aanleiding van ons e-mail account:

Is het mogelijk om extra templates te aan de plugin toe te voegen?

**Comment by hoest** [comment]
Wat bedoel je hier dan mee? Wil je de output van de tabel kunnen beïnvloeden bijvoorbeeld?

**Comment by lemodesign** [comment]
Je hebt in je plugin a folder zitten die heet "templates", hierin zit de opbouw van data. Het zou mooi zijn dat je per theme van je website deze folder zou kunnen kopiëren in je theme en dat hij automatisch kijkt welke layout (template) hij moet gebruiken voor welke theme. Dit is een groot voordeel als je wordpress Multisites gebruikt.

Ook zou het fijn zijn als je meer dan alleen de standaard .html bestanden zou kunnen gebruiken. Ik zou bijvoorbeel wedstrijd.html en wedstrijd-groot.html willen gebruiken om data op te vragen. Op deze manier heb ik meer vrijheid om te bepalen hoe de layout op de website data gaat weergeven.

**Comment by hoest** [comment]
Een instelling om de map naar de template-folder te kunnen wijzigen, lijkt
me inderdaad wel een mooie uitbreiding. Je tweede verzoek is lastiger te
realiseren. Misschien heb je al wat aan het volgende:

[knvb uri="/teams/123/results" template="results_groot.html"]

Dan heb je de mogelijkheid om eigen templates toe te kennen.

**Comment by lemodesign** [comment]
Het voorbeeld dat je aangeeft:
```
[knvb uri="/teams/123/results" template="results_groot.html"]
```

Is dit al een functie in de huidige plugin of is dit iets dat ontwikkeld moet worden?

**Comment by hoest** [comment]
Dit is een idee, en moet dan ontwikkeld worden inderdaad.

Op 2 maart 2015 10:57 schreef Remon <notifications@github.com>:

**Comment by nicoo1968** [comment]
Hoi. Het is al een tijdje rustig met de eventuele updates van de plugin. Komen er nog updates met uitbreidingen of extra templates die je kunt toepassen?

**Comment by hoest** [comment]
Hoi,

Hoorde al dat er onlangs een wijziging gedaan is in de KNVB-Api waardoor de API-WordPress plugin niet meer lijkt te werken.

Dus eerdaags zal ik eens gaan kijken wat er nu mis gaat. Hiervoor zal ik een nieuw issue aanmaken.

**Comment by nicoo1968** [comment]
Hoi Jelle,

Dat zou helemaal super zijn. ik blijf het in de gaten houden. top!

Met vriendelijke groet,,

Nico

**Comment by nicoo1968** [comment]
Hallo Jelle,

Is er al iets bekend van de plugin en de aanpassing nav de wijziging die de KNVB heeft gedaan?

met vriendelijke groet,

Nico

**Comment by hoest** [comment]
Hoi,

Nee niet echt. Nog geen tijd gehad. Hopelijk kom ik er deze week aan toe!

Groeten
Jelle

Op dinsdag 28 juli 2015 heeft nicoo1968 <notifications@github.com> het
volgende geschreven:

**Comment by nicoo1968** [comment]
Het is ook vakantietijd he, maar maakt ook niet uit ik dacht ik informeer even voor hetzelfde geldt had ik iets gemist.

**Comment by hoest** [comment]
@nicoo1968 : Zie #12

**Comment by hoest** [comment]
Sorry, dit issue moest niet gesloten worden.

**Comment by nicoo1968** [comment]
Hallo Jelle Als de plugin verder goed werkt dan heb ik nog wel een vraagerover. Ik gebruik de KNVB api plugin op http://hfc15.nl  en heb voor alle commando’s een pagina gemaakt http://hfc15.nl/senioren/zondag-5/zondag-2/test-programma/ <http://hfc15.nl/senioren/zondag-5/zondag-2/test-programma/> zodat ik kan zien of speelschema’s ook ingevuld worden wat namelijk nu niet het geval is. 

Komt dit vanzelf (dus een paar week voor de wedstrijd) of doe ik iets verkeerd met de toegepaste codes? want hij geeft wel helemaal onder wel alle te spelen wedstrijden weer maar niet individueel per team.

Ik hoop dat je kunt helpen.

Met vriendelijke groet,
Nico

**Comment by hoest** [comment]
@nicoo1968 : Om verdere vervuiling van deze wens te voorkomen heb ik voor je vraag even een apart issue geopend: #13

**Comment by hoest** [comment]
Zie #27
